### ISSUE TITLE
Bug in FRoDO.prep()

### ISSUE THREAD

**Issue by antyeates1983** [lowderchris/FRoDO#11]
Line 66 should read
compA.compa(file[-8:-3])
otherwise the file prefix is included twice when trying to read the netcdf file in the fortran code.

**Comment by lowderchris** [comment]
Could this be a difference in file naming schemes? For a sample filename I'm left with:

`'/Users/clowder/work/data/FRoDO/test/dat/b_00000_12.nc'`

```
file[-11:-3]
'00000_12'
```

**Comment by antyeates1983** [comment]
Yes, you're right. I guess this is run dependent so will need to be fixed by the user themselves.

**Comment by lowderchris** [comment]
I think then, for the moment, I'll keep that as the required filename format. This can certainly be updated.
