### ISSUE TITLE
Command line running doesn't work

### ISSUE THREAD

**Issue by antyeates1983** [lowderchris/FRoDO#12]
Running
python3 FRoDO.py
doesn't work because for some reason it tries to execute the FRoDO() subroutine first, rather than the __main__ one. Then it crashes because I haven't yet done the prep (which I had added to the top of the __main__ routine first).

**Comment by lowderchris** [comment]
I've added a bit in the README to clarify that FRoDO.prep() needs to be run separately. I thought this might be best to avoid calculating this twice, though I could just put a check to see if they already exist in that directory...

I don't seem to be having any problems running this with python3 FRoDO.py with the magnetic vector potential already computed, though I haven't checked this on a linux machine.
